### ISSUE TITLE
Úkoly 1-3 hotové 

### ISSUE THREAD

**Issue by MarketaVaj** [MarketaVaj/python-012021#1]
@pesikj úkoly 1-3 by měly být hotovy.

**Comment by pesikj** [comment]
Příklady 1 až 3 jsou super :-)

**Comment by MarketaVaj** [comment]
@pesikj ukoly 4 a 5 dodělány

**Comment by pesikj** [comment]
### 4. úkol :heavy_check_mark:

Úkol funguje, ale nemusíš správné písmeno hledat pomocí cyklu, můžeš použít hranaté závorky pro vyhledání položky ve slovníku podle klíče. Je to tak trochu jednodušší :-)

```
for i in text:
    if i == " ":
        print('/')
    else:
        if i in morseCode:
            print(morseCode[i])

```

### 5. úkol :heavy_check_mark:
​
Tady pozor na vnořenou podmínku. Jsou tam knížky, které jsou jen ve slovníku `prodeje2020`, ale nejsou ve slovníku `prodeje2019`. Pokud máš ale druhou podmínku vnořenou do první, tak pro tyto knížky program fungovat nebude. Můžeš mít třeba podmínky samostatně a následně vypsat text o tom, že knížka není na seznamu, pokud má nulové prodeje.

```
if mojekniha in prodeje2019:
    prodejcelkem += prodeje2019[mojekniha]
if mojekniha in prodeje2020:
    prodejcelkem += prodeje2020[mojekniha]

if prodejcelkem > 0:
    print('Bylo prodano ', (prodejcelkem), '.')
else:
    print('Zadana kniha neni v nasem seznamu.')
```

Shrnuti + pozadavky na upravu
​
Jsou to jen drobnosti, takže ti zapisuji 5 bodů 👍

**Comment by MarketaVaj** [comment]
Jasné rozumím a tu podmínku chápu, už jsem si to opravila. Nedošlo mně co bude dělat to vnoření. Díky za komentáře. 

Issue k první lekci zavírám.
